name = "formal-power-series"
version = "0.1.0"
defaultTargets = ["FormalPowerSeries", "Tests", "FormalPowerSeriesTests"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[require]]
name = "multivariate-polynomials"
git = "https://github.com/FormalFrontier/multivariate-polynomials.git"
rev = "b2f525056365c513029f3b0fae6d13c000a2b633"

[[lean_lib]]
name = "FormalPowerSeries"

[[lean_lib]]
name = "Tests"

[[lean_lib]]
name = "FormalPowerSeriesTests"
