/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import FormalPowerSeries.MvPowerSeries.IdealAdicRestricted
public import Mathlib.RingTheory.Valuation.ValuationRing
public import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.Ideal.Operations

public section

/-!
# Coefficient content of ideal-adically restricted series

Over a separated prevaluation ring, the ideal generated by all coefficients of
an ideal-adically restricted multivariate power series is generated by one of
its coefficients. The variables and the ideal of definition are arbitrary.
-/

set_option warningAsError true

namespace MvPowerSeries

variable {σ R : Type*} [CommRing R] [PreValuationRing R]

private theorem exists_divisor_of_finite {ι : Type*} (c : ι → R)
    (s : Finset ι) (hne : s.Nonempty) :
    ∃ j ∈ s, ∀ i ∈ s, c j ∣ c i := by
  classical
  induction s using Finset.induction_on with
  | empty => simp at hne
  | @insert a s ha ih =>
    by_cases hs : s.Nonempty
    · obtain ⟨j, hj, hjdiv⟩ := ih hs
      by_cases hja : c j ∣ c a
      · refine ⟨j, Finset.mem_insert_of_mem hj, ?_⟩
        intro i hi
        rcases Finset.mem_insert.mp hi with rfl | his
        · exact hja
        · exact hjdiv i his
      · have haj : c a ∣ c j :=
          (ValuationRing.dvd_total (c a) (c j)).resolve_right hja
        refine ⟨a, by simp, ?_⟩
        intro i hi
        rcases Finset.mem_insert.mp hi with rfl | his
        · exact dvd_refl _
        · exact haj.trans (hjdiv i his)
    · refine ⟨a, by simp, ?_⟩
      intro i hi
      rcases Finset.mem_insert.mp hi with rfl | his
      · exact dvd_refl _
      · exact (hs ⟨i, his⟩).elim

/-- A restricted series over a separated prevaluation ring has a coefficient
generating the ideal spanned by all its coefficients, including for the zero
series and for an empty variable type. -/
theorem IsAdicallyRestricted.exists_span_range_eq_span_coeff (I : Ideal R)
    [IsHausdorff I R] (f : MvPowerSeries σ R) (hf : IsAdicallyRestricted I f) :
    ∃ m : σ →₀ ℕ,
      Ideal.span (Set.range (fun j : σ →₀ ℕ => coeff j f)) =
        Ideal.span {coeff m f} := by
  classical
  by_cases hz : ∀ m : σ →₀ ℕ, coeff m f = 0
  · refine ⟨0, ?_⟩
    have hr : Set.range (fun m : σ →₀ ℕ => coeff m f) = {0} := by
      ext x
      constructor
      · rintro ⟨m, rfl⟩
        simp [hz m]
      · intro hx
        exact ⟨0, by simpa [hz] using hx.symm⟩
    rw [hr, hz 0]
  · push Not at hz
    obtain ⟨m₀, hm₀⟩ := hz
    obtain ⟨k, hk⟩ : ∃ k : ℕ, coeff m₀ f ∉ I ^ k := by
      by_contra h
      push Not at h
      apply hm₀
      apply (IsHausdorff.haus (I := I) (M := R) inferInstance)
      intro n
      apply (SModEq.zero).2
      simpa only [Ideal.smul_eq_mul, Ideal.mul_top] using h n
    let s := (hf k).toFinset
    have hs : s.Nonempty := ⟨m₀, (hf k).mem_toFinset.mpr hk⟩
    obtain ⟨m, hm, hdiv⟩ := exists_divisor_of_finite (fun j => coeff j f) s hs
    have hmk : coeff m f ∉ I ^ k := (hf k).mem_toFinset.mp hm
    have htotal : I ^ k ≤ Ideal.span {coeff m f} ∨
        Ideal.span {coeff m f} ≤ I ^ k :=
      (PreValuationRing.iff_ideal_total.mp (inferInstance : PreValuationRing R)).total _ _
    have hpow : I ^ k ≤ Ideal.span {coeff m f} := by
      rcases htotal with hle | hle
      · exact hle
      · exact (hmk (hle (Ideal.mem_span_singleton_self _))).elim
    refine ⟨m, le_antisymm ?_ ?_⟩
    · apply Ideal.span_le.mpr
      rintro x ⟨j, rfl⟩
      by_cases hj : j ∈ s
      · exact Ideal.mem_span_singleton.mpr (hdiv j hj)
      · apply hpow
        by_contra hnot
        exact hj ((hf k).mem_toFinset.mpr hnot)
    · apply Ideal.span_le.mpr
      intro x hx
      rw [Set.mem_singleton_iff] at hx
      subst x
      exact Ideal.subset_span (Set.mem_range_self m)

end MvPowerSeries
