/- SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents -/
module

public import FormalPowerSeries.MvPowerSeries.IdealAdicRestricted.DegreeDecay
public import Mathlib.RingTheory.Finiteness.Ideal
public import Mathlib.Data.Nat.Find

public section

/-!
# Finitely generated kernels of restricted-series reduction

For finitely many variables and a finitely generated coefficient ideal, the kernel
of polynomial reduction is the algebraic ideal generated by constant images of
the corresponding ideal power. The coefficient decomposition preserves restrictedness
without cancellation or regularity assumptions.
-/

set_option warningAsError true

namespace MvPowerSeries

variable {σ R : Type*} [CommRing R] [Finite σ]

set_option maxHeartbeats 800000 in
-- The finite coefficient decomposition has nested existence and support proofs.
/-- A restricted series whose coefficients lie in an ideal power admits a finite
decomposition by constant generators of that power, with restricted coefficients. -/
theorem exists_restricted_fg_decomposition (I : Ideal R) (hI : I.FG) (k : ℕ)
    (f : adicallyRestrictedSubring (σ := σ) I)
    (hf : ∀ m : σ →₀ ℕ, coeff m (f : MvPowerSeries σ R) ∈ I ^ k) :
    ∃ (n : ℕ) (v : Fin n → R)
      (g : Fin n → adicallyRestrictedSubring (σ := σ) I),
      (∀ j, v j ∈ I ^ k) ∧
        f = ∑ j, polynomialToRestricted I (MvPolynomial.C (v j)) * g j := by
  classical
  obtain ⟨n, v, hv⟩ :=
    Submodule.fg_iff_exists_fin_generating_family.mp (Ideal.FG.pow (n := k) hI)
  have hv' : Ideal.span (Set.range v) = I ^ k := hv
  have hv_mem (j : Fin n) : v j ∈ I ^ k := by
    rw [← hv']
    exact Ideal.subset_span (Set.mem_range_self j)
  let depth (m : σ →₀ ℕ) : ℕ :=
    Nat.findGreatest (fun t => coeff m (f : MvPowerSeries σ R) ∈ I ^ (k + t)) m.degree
  have hdepth (m : σ →₀ ℕ) :
      coeff m (f : MvPowerSeries σ R) ∈ I ^ (k + depth m) :=
    Nat.findGreatest_spec (P := fun t => coeff m (f : MvPowerSeries σ R) ∈ I ^ (k + t))
      (Nat.zero_le _) (by simpa using hf m)
  have hdecomp (m : σ →₀ ℕ) :
      ∃ a : Fin n →₀ R, (∀ j, a j ∈ I ^ depth m) ∧
        a.sum (fun j b => b * v j) = coeff m (f : MvPowerSeries σ R) := by
    have hm : coeff m (f : MvPowerSeries σ R) ∈
        (I ^ depth m) * Ideal.span (Set.range v) := by
      rw [hv', Ideal.mul_comm, ← pow_add]
      exact hdepth m
    obtain ⟨a, ha, heq⟩ :=
      (Submodule.mem_ideal_smul_span_iff_exists_sum (I ^ depth m) v
        (coeff m (f : MvPowerSeries σ R))).mp hm
    exact ⟨a, ha, by simpa only [smul_eq_mul] using heq⟩
  choose a ha haeq using hdecomp
  have hfinite (l : ℕ) : {m : σ →₀ ℕ | depth m < l}.Finite := by
    apply ((Finsupp.finite_of_degree_lt (σ := σ) l).union
      (((mem_adicallyRestrictedSubring I (f : MvPowerSeries σ R)).mp f.property)
        (k + l))).subset
    intro m hm
    by_contra hnot
    have hdeg : l ≤ m.degree := Nat.le_of_not_gt (fun h => hnot (Or.inl h))
    have hcoeff : coeff m (f : MvPowerSeries σ R) ∈ I ^ (k + l) := by
      by_contra hbad
      exact hnot (Or.inr hbad)
    exact (not_lt_of_ge (Nat.le_findGreatest hdeg hcoeff)) hm
  let g (j : Fin n) : adicallyRestrictedSubring (σ := σ) I :=
    ⟨(fun m => a m j : MvPowerSeries σ R),
      (mem_adicallyRestrictedSubring I _).mpr (by
        intro l
        apply (hfinite l).subset
        intro m hm
        change a m j ∉ I ^ l at hm
        by_contra hlt
        exact hm ((Ideal.pow_le_pow_right (Nat.le_of_not_gt hlt)) (ha m j)))⟩
  refine ⟨n, v, g, hv_mem, ?_⟩
  apply Subtype.ext
  apply MvPowerSeries.ext
  intro m
  have heq := haeq m
  rw [Finsupp.sum_fintype _ _ (by simp)] at heq
  have hcoe :
      ((∑ j, polynomialToRestricted I (MvPolynomial.C (v j)) * g j :
        adicallyRestrictedSubring (σ := σ) I) : MvPowerSeries σ R) =
        ∑ j, ((polynomialToRestricted I (MvPolynomial.C (v j)) * g j :
          adicallyRestrictedSubring (σ := σ) I) : MvPowerSeries σ R) :=
    by
      change (Subring.subtype _) (∑ j, polynomialToRestricted I (MvPolynomial.C (v j)) * g j) =
        ∑ j, (Subring.subtype _) (polynomialToRestricted I (MvPolynomial.C (v j)) * g j)
      exact map_sum _ _ _
  rw [hcoe]
  simp only [map_sum, Subring.coe_mul, polynomialToRestricted_coe, MvPolynomial.coe_C]
  simp only [coeff_C_mul]
  change (f : MvPowerSeries σ R) m = ∑ j, v j * a m j
  simpa only [coeff_apply, mul_comm] using heq.symm

set_option maxHeartbeats 800000 in
-- The kernel identification elaborates a finite polynomial decomposition.
/-- The kernel of reduction is the algebraic image ideal *inside* the restricted
series subring, at every ideal power including level zero. -/
theorem ker_adicReduction_fg (I : Ideal R) (hI : I.FG) (k : ℕ) :
    RingHom.ker (adicReduction (σ := σ) I k) =
      Ideal.map ((polynomialToRestricted (σ := σ) I).comp MvPolynomial.C) (I ^ k) := by
  apply le_antisymm
  · intro f hf
    have hfcoeff (m : σ →₀ ℕ) : coeff m (f : MvPowerSeries σ R) ∈ I ^ k := by
      have hzero : (adicReduction I k f).coeff m = 0 := by
        rw [(RingHom.mem_ker).mp hf]
        simp
      rw [coeff_adicReduction] at hzero
      exact Ideal.Quotient.eq_zero_iff_mem.mp hzero
    obtain ⟨n, v, g, hv, hfg⟩ := exists_restricted_fg_decomposition I hI k f hfcoeff
    rw [hfg]
    apply Submodule.sum_mem
    intro j _
    exact (Ideal.map _ (I ^ k)).mul_mem_right _ (Ideal.mem_map_of_mem _ (hv j))
  · apply Ideal.map_le_iff_le_comap.mpr
    intro a ha
    apply (RingHom.mem_ker).mpr
    change adicReduction I k (polynomialToRestricted I (MvPolynomial.C a)) = 0
    rw [adicReduction_polynomial, MvPolynomial.map_C]
    rw [Ideal.Quotient.eq_zero_iff_mem.mpr ha, map_zero]

end MvPowerSeries
